/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AutoencoderMetrics = IDL.Record({
  'f1' : IDL.Float64,
  'auc' : IDL.Float64,
  'threshold' : IDL.Float64,
  'precision' : IDL.Float64,
  'recall' : IDL.Float64,
});
export const ConfusionMatrix = IDL.Record({
  'fn' : IDL.Nat,
  'fp' : IDL.Nat,
  'tn' : IDL.Nat,
  'tp' : IDL.Nat,
});
export const EdaStats = IDL.Record({
  'fraudCases' : IDL.Nat,
  'legitimateCases' : IDL.Nat,
  'fraudRate' : IDL.Float64,
  'totalTransactions' : IDL.Nat,
});
export const FeatureImportance = IDL.Record({
  'feature' : IDL.Text,
  'importance' : IDL.Float64,
});
export const ModelScore = IDL.Record({
  'auc' : IDL.Float64,
  'name' : IDL.Text,
});
export const RocPoint = IDL.Record({
  'fpr' : IDL.Float64,
  'tpr' : IDL.Float64,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'analyzeTransaction' : IDL.Func([IDL.Vec(IDL.Float64)], [IDL.Text], []),
  'getAutoencoderMetrics' : IDL.Func([], [AutoencoderMetrics], ['query']),
  'getConfusionMatrix' : IDL.Func([], [ConfusionMatrix], ['query']),
  'getEdaStats' : IDL.Func([], [EdaStats], ['query']),
  'getFeatureImportance' : IDL.Func(
      [],
      [IDL.Vec(FeatureImportance)],
      ['query'],
    ),
  'getModelScores' : IDL.Func([], [IDL.Vec(ModelScore)], ['query']),
  'getRocCurve' : IDL.Func([], [IDL.Vec(RocPoint)], ['query']),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AutoencoderMetrics = IDL.Record({
    'f1' : IDL.Float64,
    'auc' : IDL.Float64,
    'threshold' : IDL.Float64,
    'precision' : IDL.Float64,
    'recall' : IDL.Float64,
  });
  const ConfusionMatrix = IDL.Record({
    'fn' : IDL.Nat,
    'fp' : IDL.Nat,
    'tn' : IDL.Nat,
    'tp' : IDL.Nat,
  });
  const EdaStats = IDL.Record({
    'fraudCases' : IDL.Nat,
    'legitimateCases' : IDL.Nat,
    'fraudRate' : IDL.Float64,
    'totalTransactions' : IDL.Nat,
  });
  const FeatureImportance = IDL.Record({
    'feature' : IDL.Text,
    'importance' : IDL.Float64,
  });
  const ModelScore = IDL.Record({ 'auc' : IDL.Float64, 'name' : IDL.Text });
  const RocPoint = IDL.Record({ 'fpr' : IDL.Float64, 'tpr' : IDL.Float64 });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'analyzeTransaction' : IDL.Func([IDL.Vec(IDL.Float64)], [IDL.Text], []),
    'getAutoencoderMetrics' : IDL.Func([], [AutoencoderMetrics], ['query']),
    'getConfusionMatrix' : IDL.Func([], [ConfusionMatrix], ['query']),
    'getEdaStats' : IDL.Func([], [EdaStats], ['query']),
    'getFeatureImportance' : IDL.Func(
        [],
        [IDL.Vec(FeatureImportance)],
        ['query'],
      ),
    'getModelScores' : IDL.Func([], [IDL.Vec(ModelScore)], ['query']),
    'getRocCurve' : IDL.Func([], [IDL.Vec(RocPoint)], ['query']),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };