/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AutoencoderMetrics {
  'f1' : number,
  'auc' : number,
  'threshold' : number,
  'precision' : number,
  'recall' : number,
}
export interface ConfusionMatrix {
  'fn' : bigint,
  'fp' : bigint,
  'tn' : bigint,
  'tp' : bigint,
}
export interface EdaStats {
  'fraudCases' : bigint,
  'legitimateCases' : bigint,
  'fraudRate' : number,
  'totalTransactions' : bigint,
}
export interface FeatureImportance { 'feature' : string, 'importance' : number }
export interface ModelScore { 'auc' : number, 'name' : string }
export interface RocPoint { 'fpr' : number, 'tpr' : number }
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'analyzeTransaction' : ActorMethod<[Array<number>], string>,
  'getAutoencoderMetrics' : ActorMethod<[], AutoencoderMetrics>,
  'getConfusionMatrix' : ActorMethod<[], ConfusionMatrix>,
  'getEdaStats' : ActorMethod<[], EdaStats>,
  'getFeatureImportance' : ActorMethod<[], Array<FeatureImportance>>,
  'getModelScores' : ActorMethod<[], Array<ModelScore>>,
  'getRocCurve' : ActorMethod<[], Array<RocPoint>>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];